name: Build

on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
      - "pom.xml"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: "maven"

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.7

      - name: Build
        run: mvn clean package

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: ${{ success() || failure() }}
        with:
          report_paths: './target/surefire-reports/TEST-*.xml'
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'

      - name: Publish package
        if: ${{ (github.ref_name == 'master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch' }}
        run: ./_publish.sh
        env:
          COLOSSEUM_MAVEN_URL: ${{ secrets.COLOSSEUM_MAVEN }}
          COLOSSEUM_MAVEN_USERNAME: ${{ secrets.COLOSSEUM_MAVEN_USERNAME }}
          COLOSSEUM_MAVEN_PASSWORD: ${{ secrets.COLOSSEUM_MAVEN_PASSWORD }}